//
// Assignment 4 problem 5  ----- Kevin Kovack
//

/**
 *
 * @author Kev
 */
public class FoodFatPercent extends javax.swing.JFrame {

    /**
     * Creates new form FoodFatPercent
     */
    public FoodFatPercent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWithTitle = new javax.swing.JPanel();
        calFromFood = new javax.swing.JTextField();
        gramsOfFat = new javax.swing.JTextField();
        calFromFat = new javax.swing.JTextField();
        calFromFoodTitle = new javax.swing.JLabel();
        fatFromFoodTitle = new javax.swing.JLabel();
        calFromFatTitle = new javax.swing.JLabel();
        percentCalFromFatTitle = new javax.swing.JLabel();
        percentCalFromFat = new javax.swing.JTextField();
        calculateFatButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelWithTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Fat Percent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 3, 10), java.awt.Color.blue)); // NOI18N

        calFromFat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calFromFatActionPerformed(evt);
            }
        });

        calFromFoodTitle.setText("Total Calories in your food item:");

        fatFromFoodTitle.setText("Grams of fat in your food item:");

        calFromFatTitle.setText("Total number of calories from fat:");

        percentCalFromFatTitle.setText("Percentage of calories from fat:");

        calculateFatButton.setText("Calculate fat content data");
        calculateFatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateFatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWithTitleLayout = new javax.swing.GroupLayout(panelWithTitle);
        panelWithTitle.setLayout(panelWithTitleLayout);
        panelWithTitleLayout.setHorizontalGroup(
            panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWithTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculateFatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelWithTitleLayout.createSequentialGroup()
                        .addGroup(panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(calFromFoodTitle)
                                .addComponent(calFromFatTitle)
                                .addComponent(fatFromFoodTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(percentCalFromFatTitle))
                        .addGap(18, 18, 18)
                        .addGroup(panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gramsOfFat, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(calFromFat)
                            .addComponent(percentCalFromFat)
                            .addComponent(calFromFood))))
                .addContainerGap())
        );
        panelWithTitleLayout.setVerticalGroup(
            panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWithTitleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calFromFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calFromFoodTitle))
                .addGap(18, 18, 18)
                .addGroup(panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gramsOfFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatFromFoodTitle))
                .addGap(18, 18, 18)
                .addComponent(calculateFatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calFromFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calFromFatTitle))
                .addGap(10, 10, 10)
                .addGroup(panelWithTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentCalFromFatTitle)
                    .addComponent(percentCalFromFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelWithTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelWithTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(exitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // Close program
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void calculateFatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateFatButtonActionPerformed
        // on Button click
        
        //declarations
        double myCalFromFood, myGramsOfFat, myFatFromFood, myPercentCalFromFood;
        String calFromFatText, percentCalFromFatText;
        //input
        myCalFromFood = Double.parseDouble(calFromFood.getText());
        myGramsOfFat = Double.parseDouble(gramsOfFat.getText());
        
        //processing
        myFatFromFood = 9 * myGramsOfFat;
        myPercentCalFromFood = (myFatFromFood / myCalFromFood) * 100;
        
        //output
            //format my doubles into string X.XX formats
        calFromFatText = String.format("%.2f", myFatFromFood);
        percentCalFromFatText = String.format("%.2f%%", myPercentCalFromFood);
            //push formatted strings to textfields
        calFromFat.setText(calFromFatText);
        percentCalFromFat.setText(percentCalFromFatText);
        
    }//GEN-LAST:event_calculateFatButtonActionPerformed

    private void calFromFatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calFromFatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calFromFatActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // clear textfields
        calFromFat.setText("");
        calFromFood.setText("");
        gramsOfFat.setText("");
        percentCalFromFat.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodFatPercent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodFatPercent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodFatPercent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodFatPercent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodFatPercent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calFromFat;
    private javax.swing.JLabel calFromFatTitle;
    private javax.swing.JTextField calFromFood;
    private javax.swing.JLabel calFromFoodTitle;
    private javax.swing.JButton calculateFatButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fatFromFoodTitle;
    private javax.swing.JTextField gramsOfFat;
    private javax.swing.JPanel panelWithTitle;
    private javax.swing.JTextField percentCalFromFat;
    private javax.swing.JLabel percentCalFromFatTitle;
    // End of variables declaration//GEN-END:variables
}
